app:
  day: 庆余生
  name: ${app.day}-程序员闯关大赛
server:
# port: ${random.int(10000,20000)}
  port: 9999
spring:
  thymeleaf:
    prefix: classpath:/templates
    encoding: utf-8
  mvc:
    locale: zh_CN
  application:
    name: ${app.name}  session:    timeout: 15m
    