# for ignore utf-8 bom
server:
  port: 1024
spring:
  thymeleaf:
    prefix: classpath:/templates
    encoding: utf-8
  mvc:
    locale: zh_CN
  application:
    name: ${app.name}
  session:
    timeout: 15m

app:
  day: 庆余生
  name: ${app.day}-程序员闯关大赛